spring.application.name=leavemanagement
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/leave_management
spring.datasource.username=root
<<<<<<< HEAD
spring.datasource.password=yourpassword
=======
spring.datasource.password=your_password_here
>>>>>>> e9c9f6858a9e2c84a77e7389d6c46bbc1c55f5fe

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
